import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  deviceIdFromTopic,
  isValidSignature,
  parseSignedMessage,
  readingsTopic,
  signMessage,
} from "./deviceMessages.ts";
import { ingestSchema } from "../schemas/ingest.ts";

type Vector = {
  name: string;
  secret: string;
  deviceId: string;
  topic: string;
  body: string;
  signature: string;
  payload: string;
};

// Golden vectors, regenerated by `npm run generate:signing-vectors` and mirrored by the firmware tests.
const fixture = JSON.parse(
  readFileSync(new URL("./__fixtures__/signing-vectors.v1.json", import.meta.url), "utf8"),
) as { vectors: Vector[] };
const vectors = fixture.vectors;
const [v0, , v2] = vectors as [Vector, Vector, Vector];

function flipHexDigit(hex: string, index: number) {
  const replacement = hex[index] === "0" ? "1" : "0";
  return hex.slice(0, index) + replacement + hex.slice(index + 1);
}

// The count and the pinned signature move together with the fixture, and only ever by regenerating it:
// vectors 3-5 carry turbidity, vector 6 carries an awkward wifiSsid, vector 7 carries diag + sensors, and every
// signature changed when firmwareVersion went to 0.6.0 (the version string is inside the signed body). The pinned
// literal is what stops a half-written fixture from letting every case below pass vacuously.
test("fixture holds the eight golden vectors", () => {
  assert.equal(vectors.length, 8);
  assert.equal(v0.signature, "b537560d7b8e2fd2f7ff0f52b9b86ce9ee0f413f9db798ade49d7fedd395b491");
  for (const v of vectors) assert.match(v.secret, /not-real/);
});

// The fixture is append-only: units already in the field sign these exact bytes, and the firmware suite mirrors
// them. Pinning every original signature by name (not just v0's) means a regeneration that reorders, edits or
// re-versions an old vector fails here instead of silently shifting the contract under the firmware.
const ORIGINAL_SIGNATURES: Record<string, string> = {
  "single-temperature-sample": "b537560d7b8e2fd2f7ff0f52b9b86ce9ee0f413f9db798ade49d7fedd395b491",
  "multi-sample-batch": "0d938be9a29524b48e50807c0c21256049aeb3302e23108aa6c616ba86ce9c74",
  "second-device": "5ed7c10a5da88e8028e408b8ce2740f18218b1cb31327740c7e7ad759076b7c2",
  "temperature-and-turbidity": "b83c43c26ce27fbf241f99dc476aa64f0c5e9e5fd489a2231a90ec54bfb899e4",
  "turbidity-only-sample": "b91e60947a6c12bfa0e12e469a9cdcdd15986bb16e1c31a4bf6778ed05190158",
  "turbidity-nan-omitted-in-batch": "121ccae844014528b87a08f3dafed0ecd5a908a686c6dad86e8f848441fb3c63",
  "wifi-ssid-awkward": "8b3f6a8336e8659e909fb66698ab1ff483f33c29e3d8633687b742742d5070ed",
  "diagnostics-and-sensor-status": "7970b61b299fcf13afe3d807331773b64cb6065907f742d82554b6b312631e7c",
};

test("original 8 golden vectors are pinned byte-for-byte (append-only)", () => {
  const expected = Object.entries(ORIGINAL_SIGNATURES);
  assert.equal(expected.length, 8);
  expected.forEach(([name, signature], i) => {
    const v = vectors[i];
    assert.ok(v, `vector ${i} (${name}) is missing`);
    assert.equal(v.name, name, `vector ${i} name`);
    assert.equal(v.signature, signature, `vector ${i} (${name}) signature`);
  });
});

for (const v of vectors) {
  test(`valid golden vector "${v.name}" round-trips`, (t) => {
    assert.equal(signMessage(v.secret, v.topic, v.body), v.payload);
    assert.deepEqual(parseSignedMessage(Buffer.from(v.payload)), { signature: v.signature, body: v.body });
    assert.equal(isValidSignature(v.secret, v.topic, v.body, v.signature), true);
    assert.equal(readingsTopic(v.deviceId), v.topic);
    assert.equal(deviceIdFromTopic(v.topic), v.deviceId);

    t.mock.timers.enable({ apis: ["Date"], now: Date.parse("2023-11-15T00:00:00Z") });
    assert.equal(ingestSchema.safeParse(JSON.parse(v.body)).success, true);
  });
}

test("tampered body is rejected", () => {
  const tampered = v0.body.replace("27.5", "27.6");
  assert.notEqual(tampered, v0.body);
  assert.equal(isValidSignature(v0.secret, v0.topic, tampered, v0.signature), false);
});

test("tampered topic (signature moved to another device's topic) is rejected", () => {
  assert.notEqual(v2.topic, v0.topic);
  assert.equal(isValidSignature(v0.secret, v2.topic, v0.body, v0.signature), false);
});

test("tampered signature (one hex digit changed) is rejected", () => {
  assert.equal(isValidSignature(v0.secret, v0.topic, v0.body, flipHexDigit(v0.signature, 10)), false);
});

test("wrong key is rejected", () => {
  assert.notEqual(v2.secret, v0.secret);
  assert.equal(isValidSignature(v2.secret, v0.topic, v0.body, v0.signature), false);
});

test("malformed payloads are rejected by parseSignedMessage", async (t) => {
  const cases: Array<[string, Buffer]> = [
    ["missing v1. prefix", Buffer.from(v0.payload.slice(3))],
    ["v2. prefix", Buffer.from("v2." + v0.payload.slice(3))],
    ["separator at index 67 replaced", Buffer.from(v0.payload.slice(0, 67) + "x" + v0.payload.slice(68))],
    ["signature truncated to 63 chars", Buffer.from(`v1.${v0.signature.slice(0, 63)}.${v0.body}`)],
    ["empty buffer", Buffer.alloc(0)],
  ];
  for (const [name, payload] of cases) {
    await t.test(`malformed: ${name}`, () => {
      assert.equal(parseSignedMessage(payload), null);
    });
  }
});

test("malformed hex signature is rejected: non-hex character", () => {
  const withZ = "z" + v0.signature.slice(1);
  assert.equal(withZ.length, 64);
  assert.equal(isValidSignature(v0.secret, v0.topic, v0.body, withZ), false);
});

test("malformed hex signature is rejected: odd length (63 chars)", () => {
  assert.equal(isValidSignature(v0.secret, v0.topic, v0.body, v0.signature.slice(0, 63)), false);
});

test("deviceIdFromTopic rejects wrong prefix, wrong suffix and non-UUID ids", () => {
  assert.equal(deviceIdFromTopic(v0.topic.replace("truaquality/v1/", "truaquality/v2/")), null);
  assert.equal(deviceIdFromTopic(v0.topic.replace("/readings", "/status")), null);
  assert.equal(deviceIdFromTopic(readingsTopic("not-a-uuid")), null);
});

test("deviceIdFromTopic lowercases an uppercase UUID", () => {
  assert.equal(deviceIdFromTopic(readingsTopic("ABCDEF00-0000-4000-8000-00000000000A")), "abcdef00-0000-4000-8000-00000000000a");
});

test("characterization: uppercase hex signature is accepted", () => {
  // Pinned current behavior, not an endorsement: Buffer.from(hex) is case-insensitive, same MAC bytes.
  assert.equal(isValidSignature(v0.secret, v0.topic, v0.body, v0.signature.toUpperCase()), true);
});

test("characterization: empty body after the separator parses as an empty string", () => {
  // Pinned current behavior, not an endorsement: framing accepts it; ingestSchema rejects it later.
  assert.deepEqual(parseSignedMessage(Buffer.from(`v1.${v0.signature}.`)), { signature: v0.signature, body: "" });
});

test("characterization: trailing non-hex junk after a valid signature is accepted by isValidSignature", () => {
  // Pinned current behavior, not an endorsement: unreachable on the wire because parseSignedMessage slices
  // exactly 64 chars, and Buffer.from(hex) stops at the first non-hex character.
  assert.equal(isValidSignature(v0.secret, v0.topic, v0.body, v0.signature + "zz"), true);
});
